PDP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from pdp_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^pdp_app/', include('pdp_app.urls')),
]

pdp_app/urls.py
from django.conf.urls import url, include
from pdp_app import views

app_name = 'pdp_app'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^qa/$', views.PostListView.as_view(), name='posts'),
    url(r'^qa/(?P<pk>\d+)', views.PostDetailView.as_view(), name='post-detail'),
    url(r'^add_post/', views.add_post, name='addpost'),
    url(r'^add_comment/(?P<pk>\d+)$', views.add_comment, name='addcomment'),
    url(r'^remove_post/(?P<pk>\d+)/$', views.PostDelete.as_view(), name='removepost'),
    url(r'^state/(?:(?P<state_name>.+)/)?$', views.state, name='state-detail'),
]

pdp_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    text = models.TextField()
    author = models.CharField(max_length=40)
    post = models.ForeignKey(Post, related_name="comments")

    def __str__(self):
        return self.text

class State(models.Model):
    name = models.CharField(max_length=40)
    numpdp = models.IntegerField()
    cost = models.FloatField()

    def __str__(self):
        return self.name

pdp_app/forms.py
from django import forms
from pdp_app.models import Post, Comment
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
   
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author']
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['post']

pdp_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from pdp_app.models import Post, Comment, State
from pdp_app import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_list_or_404, get_object_or_404
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

# Create your views here.
def index(request):
    return render(request, 'pdp_app/index.html')
    
def register(request):

    registered = False

    if request.method == 'POST':

        user_form = forms.UserForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True

        else:
            print(user_form.errors)

    else:
        user_form = forms.UserForm()

    return render(request,'pdp_app/registration.html',
                          {'user_form':user_form, 'registered':registered})


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'post_list'   # your own name for the list as a template variable
    template_name = 'pdp_app/qa.html'  # Specify your own template name/location
    
class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    context_object_name = 'post'   # your own name for the list as a template variable
    template_name = 'pdp_app/post_detail.html'  # Specify your own template name/location

@login_required
def add_post(request):
    
    if request.method == 'POST':
        post_form = forms.PostForm(data=request.POST)

        if post_form.is_valid():
            
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('pdp_app:posts'))
        else: 
            print(post_form.errors)
    else:
        post_form = forms.PostForm()
    
    return render(request,'pdp_app/add_post.html',
                          {'post_form':post_form })

@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        comment_form = forms.CommentForm(data=request.POST)

        if comment_form.is_valid():
            
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse('pdp_app:posts'))
        else: 
            print(comment_form.errors)
    else:
        comment_form = forms.CommentForm()

    return render(request,'pdp_app/add_comment.html',
                          {'comment_form':comment_form, 'post':post})

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('pdp_app:posts')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(reverse('pdp_app:posts'))

def state(request, state_name):
    state = get_object_or_404(State, name=state_name)

    return render(request,'pdp_app/state-detail.html',
                          {'state':state})

templates/pdp_app/add_comment.html
<!DOCTYPE html>
{% extends "pdp_app/base.html" %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <h2> Add your post below. </h2>
          {{ comment_form.as_p }}
          <input type="submit" name="" value="Comment!">
        </form>

    </div>

  </div>

{% endblock %}

templates/pdp_app/add_post.html
<!DOCTYPE html>
{% extends "pdp_app/base.html" %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ post_form.as_p }}
          <input type="submit" name="" value="Publish!">
        </form>

    </div>

  </div>

{% endblock %}

templates/pdp_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static "css/style.css" %}"/>
  </head>

  <body>
    
    <nav id="bar" class="navbar navbar-default navbar-static-top">
   
        <ul class="nav navbar-nav pull-left">

          <li><a id="ngr" class="navbar-brand" href="{% url 'index' %}">Northrop Grumman PDP</a></li>
          <li><a id="ngr" class="navbar-link" href="{% url 'pdp_app:posts' %}">Q&A</a></li>
          
          {% if user.is_authenticated %}
              <li><a id="ngr" class="navbar-link" href="{% url 'logout' %}?next={% url 'index' %}">Logout</a></li>
          {% else %}
              <li><a id="ngr" class="navbar-link" href="{% url 'pdp_app:register' %}">Register</a></li>
              <li><a id="ngr" class="navbar-link" href="{% url 'login' %}">Login</a></li>
          {% endif %}
    
        </ul>   
    </nav>


    <div id="hello">
          {% if user.is_authenticated %}
                    <h1 id="hello">Hello, {{user.username}}</h1>
          {% endif %}
    </div>


    <div class="container" id="body">
        {% block body_block %}
            
        {% endblock %}
    </div>

    <div class="footer">
        <div class="row">
            <div id="copy" class="col-lg-6">
                    <a id="qa" href="https://www.bhavikbhatt.github.io/Personal-Website">Bhavik Bhatt 2017</a>
            </div>
            <div id="faq" class="col-lg-6">
                    <a id="qa" href="http://www.northropgrumman.com/Careers/StudentsAndNewGrads/Pages/StudentsNewGradsFAQs.aspx">Student FAQs</a>
            </div>
        </div>
    </div>

  </body>

</html>

templates/pdp_app/index.html
<!DOCTYPE html>
{% extends "pdp_app/base.html" %}
{% block body_block %}
    <script src="http://cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datamaps/0.5.8/datamaps.all.min.js"></script>
    
    <div id="container" style="position:relative; width:100%; height:700px; margin:auto;"></div>
    
    <script>
        var map = new Datamap({
            element: document.getElementById('container'),
            scope: 'usa',
            geographyConfig: {
            highlightBorderColor: '#bada55',
            popupTemplate: function(geography, data) {
            return  '<div class="hoverinfo"><strong>'  + geography.properties.name + ' - ' + ' PDP Employees:' +  data.numberOfPDPs + ' '
        },
        highlightBorderWidth: 3
    },
            fills: {
                HIGH: '#154d99',
                LOW: '#77b1ff',
                MEDIUM: '#197aff',
                defaultFill: "#b7d6ff"
            },

            data:{
                "IN": {
                    "fillKey": "LOW",
                    "numberOfPDPs": 10
                },
                "TX": {
                    "fillKey": "HIGH",
                    "numberOfPDPs": 53
                },
                "MS": {
                    "fillKey": "LOW",
                    "numberOfPDPs": 0
                },
                "GA": {
                    "fillKey": "MEDIUM",
                    "numberOfPDPs": 37
                },
                "TN": {
                    "fillKey": "LOW",
                    "numberOfPDPs": 6
                },
                "MI": {
                    "fillKey": "MEDIUM",
                    "numberOfPDPs": 21
                },
                "NC": {
                    "fillKey": "MEDIUM",
                    "numberOfPDPs": 21
                },
            },

            done: function(datamap) {
                datamap.svg.selectAll('.datamaps-subunit').on('click', function(geography) {
                    var name = geography.properties.name.toString();
                    var url_mask = "{% url 'pdp_app:state-detail' 12345 %}".replace(/12345/, geography.properties.name);
                    window.location.replace(url_mask);
                });
            }   
        });
    </script> 
{% endblock %}

templates/pdp_app/post_confirm_delete.html
<div class="container">

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object}}"?</p>
        <input type="submit" value="Confirm" />
    </form>
</div>

templates/pdp_app/post_detail.html
{% extends "pdp_app/base.html" %}

{% block body_block %}

  <h1>{{ post.title }} <a href="{% url 'pdp_app:removepost' post.id %}" class="btn btn-primary btn-md active" role="button" aria-pressed="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a> </h1>
  <h3> {{ post.text }} </h3>
  <p><strong>Author:</strong> {{ post.author }}</p>  <!-- author detail link not yet defined -->

  <div>
    <h4>Comments</h4>
    {% for comment in post.comments.all %}
    <div style="padding:0px" class="jumbotron">
       <p>{{comment.text }}</p>
       <p style="text-align: right">Author: <strong> {{comment.author }} </strong></p>
    </div>
    {% endfor %}
  </div>

   <div class="container">


       <a href="{% url 'pdp_app:addcomment' post.id %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add Comment</a>


  </div>


{% endblock %}

templates/pdp_app/qa.html
{% extends "pdp_app/base.html" %}

{% block body_block %}
    <h1>Posts</h1>

    {% if post_list %}
    <ul>

      {% for post in post_list %}
      <li>
        
        <a href="{{ post.id }}">{{ post.title }}</a> ({{post.author}})
      </li> 
      {% endfor %}

    </ul>

    <a href="{% url 'pdp_app:addpost' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add Post</a>


    {% else %}
    <p>There are no posts.</p>
    <a href="{% url 'pdp_app:addpost' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add Post</a>

    {% endif %}       
    
{% endblock %}

templates/pdp_app/registration.html
<!DOCTYPE html>
{% extends "pdp_app/base.html" %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
        <h2><a href="{% url 'login' %}">Login Here</a></h2>
      {% else %}
        <h1>Register Here</h1>
        <h3>Fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

templates/pdp_app/state-detail.html
{% extends "pdp_app/base.html" %}

{% block body_block %}

    <div class="container">
        <div class="jumbotron">
        
            <h1>{{state.name}} </h1>
        </div>
    </div>







{% endblock %}